name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparation
        uses: ./.github/actions/preparation
        with:
          python-version: "3.11"

      - name: Linting
        uses: ./.github/actions/lint

      - name: Tests
        uses: ./.github/actions/tests
